auth:
  createAdminUser: true
  existingSecret: "${auth_secret}"
  adminUser: "${admin_username}"
  managementUser: "${management_username}"
  tls:
    enabled: false

serviceDiscovery:
  enabled: %{ if replica_count > 1 } true %{ else } false %{ endif }

cache:
  ownersCount: ${replica_count}
  authOwnersCount: ${replica_count}

keycloakConfigCli:
  enabled: false

replicaCount: ${replica_count}

service:
    type: ClusterIP

ingress:
  enabled: ${ingress_enabled}
  hostname: "${ingress_host}"
  certManager: false
  tls: false
  networkPolicy:
    enabled: false

serviceAccount:
  create: true

rbac:
  create: false

pdb:
  create: false

autoscaling:
  enabled: false

metrics:
  enabled: ${prometheus_enabled}
  service:
    port: 9990
  serviceMonitor:
    enabled: false

postgresql:
  enabled: false

externalDatabase:
  host: "${database_host}"
  port: 5432
  database: "${database_name}"
  user: "${database_username}"
