postgresqlPostgresPassword: postgres
postgresqlUsername: "${username}"
postgresqlDatabase: "${database}"
existingSecret: "${database_secret}"

image:
  tag: "${image_tag}"

replication:
  enabled: false

service:
  type: ClusterIP
  port: 5432

persistence:
  storageClass: "${persistence_storage_class}"
  size: "${persistence_size}"

volumePermissions:
  enabled: true

service:
  type: "${service_type}"
  nodePort: ${service_node_port}
  clusterIP: "${service_cluster_ip}"
  loadBalancerIP: "${service_load_balancer_ip}"

metrics:
  enabled: ${prometheus_enabled}
