controller:
  daemonMemoryLimit: "${controller_daemon_memory_limit}"
  configOptions: "${controller_config_options}"
  extraEnvVars: %{ if length(controller_extra_env_vars) == 0 } [] %{ else }
    %{ for extra_env_var in controller_extra_env_vars ~}
    - "${extra_env_var}"
    %{ endfor ~}
  %{ endif }
  resources:
    limits: %{ if length(controller_resources_limits) == 0 } {} %{ else }
      %{ for k, v in controller_resources_limits ~}
      ${k}: "${v}"
      %{ endfor ~}
    %{ endif }
    requests: %{ if length(controller_resources_requests) == 0 } {} %{ else }
      %{ for k, v in controller_resources_requests ~}
      ${k}: "${v}"
      %{ endfor ~}
    %{ endif }

worker:
  replicaCount: ${replica_count}
  javaOptions: "${worker_java_options}"
  configOptions: "${worker_config_options}"
  daemonMemoryLimit: "${worker_daemon_memory_limit}"
  memoryLimit: "${worker_memory_limit}"
  coreLimit: "${worker_core_limit}"
  resources:
    limits: %{ if length(worker_resources_limits) == 0 } {} %{ else }
      %{ for k, v in worker_resources_limits ~}
      ${k}: "${v}"
      %{ endfor ~}
    %{ endif }
    requests: %{ if length(worker_resources_requests) == 0 } {} %{ else }
      %{ for k, v in worker_resources_requests ~}
      ${k}: "${v}"
      %{ endfor ~}
    %{ endif }

ingress:
  enabled: ${ingress_enabled}
  hostname: "${ingress_host}"
  tls: false

metrics:
  enabled: ${prometheus_enabled}
  podMonitor:
    enabled: false