controller:
  initializeOnce: true
  ingress:
    enabled: ${ingress_enabled}
    hostName: ${ingress_host}
  additionalPlugins: %{ if length(additional_plugins) == 0 } [] %{ else }
    %{ for plugin in additional_plugins ~}
    - "${plugin}"
    %{ endfor ~}
  %{ endif }

prometheus:
  enabled: ${prometheus_enabled}

agent:
  alwaysPullImage: true

persistence:
  enabled: true
  accessMode: "ReadWriteOnce"
  size: "${persistence_size}"
  storageClass: "${persistence_storage_class}"

rbac:
  create: true
#  name: jenkins
#  annotations: {}

serviceAccount:
  create: true
#  name: jenkins
#  annotations: {}

backup:
  enabled: false
