server:
  enabled: true
  global:
    scrape_interval: ${prometheus_scrape_interval}
    scrape_timeout: ${prometheus_scrape_timeout}
    evaluation_interval: ${prometheus_evaluation_interval}
  ingress:
    enabled: false
  persistentVolume:
    enabled: true
    storageClass: "${prometheus_persistence_storage_class}"
    size: "${prometheus_persistence_size}"
  replicaCount: ${prometheus_replica_count}

kubeStateMetrics:
  enabled: ${kube_state_metrics_enabled}

nodeExporter:
  enabled: ${node_exporter_enabled}

alertmanager:
  enabled: ${alert_manager_enabled}
  #baseURL: ""
  ingress:
    enabled: false
  persistentVolume:
    enabled: true
    storageClass: "${alert_manager_persistence_storage_class}"
    size: "${alert_manager_persistence_size}"
  replicaCount: ${alert_manager_replica_count}

pushgateway:
  enabled: ${push_gateway_enabled}
  ingress:
    enabled: false
  replicaCount: ${push_gateway_replica_count}
  persistentVolume:
    enabled: false

configmapReload:
  alertmanager:
    enabled: ${alert_manager_enabled}
  prometheus:
    enabled: true

